/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1;

/**
 *
 * @author Jerry
 *
 */
public class AssuranceFrame extends javax.swing.JFrame {

    /**
     * Creates new form AssuranceFrame
     */
    public AssuranceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupSexe = new javax.swing.ButtonGroup();
        sitBG1 = new javax.swing.ButtonGroup();
        sitBG2 = new javax.swing.ButtonGroup();
        sitBG3 = new javax.swing.ButtonGroup();
        sitBG4 = new javax.swing.ButtonGroup();
        sitBG5 = new javax.swing.ButtonGroup();
        sitBG6 = new javax.swing.ButtonGroup();
        bGroupRabais = new javax.swing.ButtonGroup();
        jScrollMain = new javax.swing.JScrollPane();
        jPanelMain = new javax.swing.JPanel();
        jSep1 = new javax.swing.JSeparator();
        jSep2 = new javax.swing.JSeparator();
        jSep3 = new javax.swing.JSeparator();
        jSep4 = new javax.swing.JSeparator();
        jPanelInfo = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextPrenom = new javax.swing.JTextField();
        jTextNom = new javax.swing.JTextField();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();
        jLabelDOB = new javax.swing.JLabel();
        jFTextDOB = new javax.swing.JFormattedTextField();
        jLabelTele = new javax.swing.JLabel();
        jFTextTelephone = new javax.swing.JFormattedTextField();
        jLabelAdresse = new javax.swing.JLabel();
        jTextAdresse = new javax.swing.JTextField();
        jLabelCourriel = new javax.swing.JLabel();
        jTextCourriel = new javax.swing.JTextField();
        jPanelVec = new javax.swing.JPanel();
        jLabelVec = new javax.swing.JLabel();
        jLabelAnnee = new javax.swing.JLabel();
        jComboAnnee = new javax.swing.JComboBox<>();
        jLabelMarque = new javax.swing.JLabel();
        jComboMarque = new javax.swing.JComboBox<>();
        jLabelModel = new javax.swing.JLabel();
        jComboModel = new javax.swing.JComboBox<>();
        jLabelKM = new javax.swing.JLabel();
        jComboKM = new javax.swing.JComboBox<>();
        jPanelAnti = new javax.swing.JPanel();
        jLabelAnti = new javax.swing.JLabel();
        jCheckAlarme = new javax.swing.JCheckBox();
        jCheckAnti = new javax.swing.JCheckBox();
        jCheckMarquage = new javax.swing.JCheckBox();
        jCheckSys = new javax.swing.JCheckBox();
        jCheckAutre = new javax.swing.JCheckBox();
        jCheckAucun = new javax.swing.JCheckBox();
        jPanelSit = new javax.swing.JPanel();
        jLabelSitTitle = new javax.swing.JLabel();
        jLabelSit1 = new javax.swing.JLabel();
        jLabelSit2 = new javax.swing.JLabel();
        jLabelSit3 = new javax.swing.JLabel();
        jLabelSit4 = new javax.swing.JLabel();
        jLabelSit5 = new javax.swing.JLabel();
        jLabelSit6 = new javax.swing.JLabel();
        jRBSit1Y = new javax.swing.JRadioButton();
        jRBSit1N = new javax.swing.JRadioButton();
        jRBSit2Y = new javax.swing.JRadioButton();
        jRBSit2N = new javax.swing.JRadioButton();
        jRBSit3Y = new javax.swing.JRadioButton();
        jRBSit3N = new javax.swing.JRadioButton();
        jRBSit4Y = new javax.swing.JRadioButton();
        JrbSit4N = new javax.swing.JRadioButton();
        jRBSit5Y = new javax.swing.JRadioButton();
        jRBSit5N = new javax.swing.JRadioButton();
        jRBSit6Y = new javax.swing.JRadioButton();
        jRBSit6N = new javax.swing.JRadioButton();
        jPanelHabi = new javax.swing.JPanel();
        jLabelHabi = new javax.swing.JLabel();
        jScrollPaneHabi = new javax.swing.JScrollPane();
        jTextPaneHabi = new javax.swing.JTextPane();
        jRadioHabiY = new javax.swing.JRadioButton();
        jRadioHabiN = new javax.swing.JRadioButton();
        jPanelFin = new javax.swing.JPanel();
        jButtonSub = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(554, 1350));

        jScrollMain.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollMain.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setText("Information de base");

        jTextPrenom.setText("Prenom");
        jTextPrenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPrenomMouseClicked(evt);
            }
        });

        jTextNom.setText("Nom");
        jTextNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNomMouseClicked(evt);
            }
        });

        bGroupSexe.add(jRadioMale);
        jRadioMale.setText("Male");

        bGroupSexe.add(jRadioFemale);
        jRadioFemale.setText("Female");

        jLabelDOB.setText("Date de naissance");

        jFTextDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFTextDOB.setText("Jan 1, 1970");

        jLabelTele.setText("Numero telephone");

        try {
            jFTextTelephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTextTelephone.setText("123-456-7890");
        jFTextTelephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTextTelephoneMouseClicked(evt);
            }
        });

        jLabelAdresse.setText("Adresse complete");

        jTextAdresse.setText("1111 rue de la Redondance, Sherbrooke, PQ J1J 1J1");
        jTextAdresse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAdresseMouseClicked(evt);
            }
        });

        jLabelCourriel.setText("Adresse courriel");

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCourriel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelTitle))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioFemale)
                            .addComponent(jRadioMale)
                            .addComponent(jLabelTele))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFTextDOB, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jTextAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabelAdresse))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabelCourriel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioMale)
                    .addComponent(jLabelDOB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioFemale)
                    .addComponent(jFTextDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTele)
                    .addComponent(jFTextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCourriel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCourriel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelVec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelVec.setText("A propos du vehicule");

        jLabelAnnee.setText("Annee");

        jComboAnnee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017", "2016", "2015 et avant" }));

        jLabelMarque.setText("Marque");

        jComboMarque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dodge", "Jeep", "GMC", "Ram", "Nissan", "Hyundai", "Chevrolet", "Honda", "Toyota", "Ford" }));
        jComboMarque.setSelectedItem("");

        jLabelModel.setText("Model");

        jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1234567890", "abc", "def" }));

        jLabelKM.setText("KM annuelle");

        jComboKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15000 et moins", "15001 - 20000", "20001 - 25000", "25001 - 30000", "30001 - 35000", "35001 - 40000", "40001 - 45000", "45001 - 50000", "50001 - 55000", "55001 - 60000", "60001 - 65000", "65001 - 70000", "70001 - 75000", "75001 - 80000", "80001 - 85000", "85001 - 90000", "90001 - 95000", "95001 - 100000", "100000 et plus" }));

        javax.swing.GroupLayout jPanelVecLayout = new javax.swing.GroupLayout(jPanelVec);
        jPanelVec.setLayout(jPanelVecLayout);
        jPanelVecLayout.setHorizontalGroup(
            jPanelVecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnnee)
                    .addComponent(jComboMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMarque)
                    .addComponent(jLabelModel)
                    .addComponent(jComboModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVec)
                    .addComponent(jLabelKM))
                .addContainerGap())
        );
        jPanelVecLayout.setVerticalGroup(
            jPanelVecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAnnee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMarque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelAnti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAnti.setText("Systems antivols");

        jCheckAlarme.setText("Alarme sonore");

        jCheckAnti.setText("Antidemarreur");

        jCheckMarquage.setText("Marquage intensif antivol");

        jCheckSys.setText("Systeme d'alarme de reperage");

        jCheckAutre.setText("Autre");

        jCheckAucun.setText("Aucun");

        javax.swing.GroupLayout jPanelAntiLayout = new javax.swing.GroupLayout(jPanelAnti);
        jPanelAnti.setLayout(jPanelAntiLayout);
        jPanelAntiLayout.setHorizontalGroup(
            jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckAnti)
                    .addComponent(jCheckAlarme)
                    .addComponent(jCheckSys)
                    .addComponent(jCheckAutre)
                    .addComponent(jCheckAucun)
                    .addGroup(jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelAnti)
                        .addComponent(jCheckMarquage)))
                .addContainerGap())
        );
        jPanelAntiLayout.setVerticalGroup(
            jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAnti)
                .addGap(27, 27, 27)
                .addComponent(jCheckAlarme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckAnti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckMarquage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckSys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckAutre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckAucun)
                .addContainerGap())
        );

        jLabelSitTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSitTitle.setText("Situation du conducteur");

        jLabelSit1.setText("3 conducteurs/vechicules et plus");

        jLabelSit2.setText("Suspension de permis dans les 3 dernieres annees");

        jLabelSit3.setText("L'existence d'un dossier criminel");

        jLabelSit4.setText("Police d'assurance auto ou residentielle resiliee/refusee dans les 5 dernieres annees");

        jLabelSit5.setText("Conducteur perincipal detient un permis d'apprenti");

        jLabelSit6.setText("La valeur de votre vehicule est egale ou superieure a 100 000$");

        sitBG1.add(jRBSit1Y);
        jRBSit1Y.setText("Oui");

        sitBG1.add(jRBSit1N);
        jRBSit1N.setText("Non");

        sitBG2.add(jRBSit2Y);
        jRBSit2Y.setText("Oui");

        sitBG2.add(jRBSit2N);
        jRBSit2N.setText("Non");

        sitBG3.add(jRBSit3Y);
        jRBSit3Y.setText("Oui");

        sitBG3.add(jRBSit3N);
        jRBSit3N.setText("Non");

        sitBG4.add(jRBSit4Y);
        jRBSit4Y.setText("Oui");

        sitBG4.add(JrbSit4N);
        JrbSit4N.setText("Non");

        sitBG5.add(jRBSit5Y);
        jRBSit5Y.setText("Oui");

        sitBG5.add(jRBSit5N);
        jRBSit5N.setText("Non");

        sitBG6.add(jRBSit6Y);
        jRBSit6Y.setText("Oui");
        jRBSit6Y.setActionCommand("jRadioButton0");

        sitBG6.add(jRBSit6N);
        jRBSit6N.setText("Non");

        javax.swing.GroupLayout jPanelSitLayout = new javax.swing.GroupLayout(jPanelSit);
        jPanelSit.setLayout(jPanelSitLayout);
        jPanelSitLayout.setHorizontalGroup(
            jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSit6)
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addComponent(jRBSit6Y)
                        .addGap(245, 245, 245)
                        .addComponent(jRBSit6N))
                    .addComponent(jRBSit4Y)
                    .addComponent(jLabelSit4)
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSit3)
                            .addComponent(jRBSit3Y))
                        .addGap(109, 109, 109)
                        .addComponent(jRBSit3N))
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBSit2Y)
                            .addComponent(jLabelSit2))
                        .addGap(2, 2, 2)
                        .addComponent(jRBSit2N))
                    .addComponent(jLabelSit1)
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addComponent(jRBSit1Y)
                        .addGap(246, 246, 246)
                        .addComponent(jRBSit1N))
                    .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRBSit5Y)
                            .addComponent(jLabelSit5)
                            .addGroup(jPanelSitLayout.createSequentialGroup()
                                .addGap(293, 293, 293)
                                .addComponent(jRBSit5N)))
                        .addGroup(jPanelSitLayout.createSequentialGroup()
                            .addGap(293, 293, 293)
                            .addComponent(JrbSit4N)))
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabelSitTitle)))
                .addContainerGap())
        );
        jPanelSitLayout.setVerticalGroup(
            jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSitTitle)
                .addGap(18, 18, 18)
                .addComponent(jLabelSit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSit1Y)
                    .addComponent(jRBSit1N))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSit2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSit2Y)
                    .addComponent(jRBSit2N))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSit3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSit3Y)
                    .addComponent(jRBSit3N))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSit4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSit4Y)
                    .addComponent(JrbSit4N))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSit5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBSit5Y)
                    .addComponent(jRBSit5N))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSitLayout.createSequentialGroup()
                        .addComponent(jLabelSit6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBSit6Y))
                    .addComponent(jRBSit6N, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jLabelHabi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHabi.setText("Rabais habitation");

        jTextPaneHabi.setEditable(false);
        jTextPaneHabi.setBackground(new java.awt.Color(240, 240, 240));
        jTextPaneHabi.setBorder(null);
        jTextPaneHabi.setText("Si votre habitation est assurée avec nous, nous vous offrons un rabais. Voulez-vous inclure ce rabais à votre soumission?");
        jScrollPaneHabi.setViewportView(jTextPaneHabi);

        bGroupRabais.add(jRadioHabiY);
        jRadioHabiY.setText("Oui");

        bGroupRabais.add(jRadioHabiN);
        jRadioHabiN.setText("Non");

        javax.swing.GroupLayout jPanelHabiLayout = new javax.swing.GroupLayout(jPanelHabi);
        jPanelHabi.setLayout(jPanelHabiLayout);
        jPanelHabiLayout.setHorizontalGroup(
            jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHabiLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabelHabi))
                    .addComponent(jScrollPaneHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHabiLayout.createSequentialGroup()
                        .addComponent(jRadioHabiY)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioHabiN)
                        .addGap(135, 135, 135)))
                .addContainerGap())
        );
        jPanelHabiLayout.setVerticalGroup(
            jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHabi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioHabiY)
                    .addComponent(jRadioHabiN))
                .addContainerGap())
        );

        jButtonSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSub.setText("Soumission");

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancel.setText("Annuler");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCancelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFinLayout = new javax.swing.GroupLayout(jPanelFin);
        jPanelFin.setLayout(jPanelFinLayout);
        jPanelFinLayout.setHorizontalGroup(
            jPanelFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSub)
                .addGap(55, 55, 55)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );
        jPanelFinLayout.setVerticalGroup(
            jPanelFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSub)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSep2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSep1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSep3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSep4, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanelVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelAnti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelSit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jPanelFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAnti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSep2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelSit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSep3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelHabi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSep4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollMain.setViewportView(jPanelMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1205, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextAdresseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAdresseMouseClicked
        // TODO add your handling code here:
        if ("1111 rue de la Redondance, Sherbrooke, PQ J1J 1J1".equals(this.jTextAdresse.getText())) {
            jTextAdresse.setText("");
        }

    }//GEN-LAST:event_jTextAdresseMouseClicked

    private void jFTextTelephoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextTelephoneMouseClicked
        // TODO add your handling code here:
        if ("123-456-7890".equals(this.jFTextTelephone.getText())) {
            jFTextTelephone.setText("");
        }
    }//GEN-LAST:event_jFTextTelephoneMouseClicked

    private void jTextNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNomMouseClicked
        // TODO add your handling code here:
        if ("Nom".equals(this.jTextNom.getText())) {
            jTextNom.setText("");
        }
    }//GEN-LAST:event_jTextNomMouseClicked

    private void jTextPrenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPrenomMouseClicked
        // TODO add your handling code here:
        if ("Prenom".equals(this.jTextPrenom.getText())) {
            jTextPrenom.setText("");
        }
    }//GEN-LAST:event_jTextPrenomMouseClicked

    private void jButtonCancelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCancelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AssuranceFrame().setVisible(true);

                AssuranceFrame af = new AssuranceFrame();
                Assurance a = new Assurance();

                af.setVisible(true);

                if (af.jButtonSub.isSelected()) {

                    a.setPrenom(af.jTextPrenom.getText());
                    a.setNom(af.jTextNom.getText());

                    if (af.jRadioFemale.isSelected()) {
                        a.setSexe('f');
                    } else {
                        a.setSexe('m');
                    }
                    
                    

                    a.setDdn(af.jFTextDOB.getText());
                    a.setTelNum(af.jFTextTelephone.getText());
                    a.setAdresse(af.jTextAdresse.getText());
                    a.setEmail(af.jTextCourriel.getText());
                    a.setVecYear(String.valueOf(af.jComboAnnee.getSelectedItem()));
                    a.setVecMake(String.valueOf(af.jComboMarque.getSelectedItem()));
                    a.setVecMod(String.valueOf(af.jComboModel.getSelectedItem()));
                    a.setKmPerYr(String.valueOf(af.jComboKM.getSelectedItem()));

                    Boolean[] antiVol = new Boolean[6];
                    for (int i = 0; i < 6; i++) {
                        antiVol[i] = false;
                    }

                    if (af.jCheckAlarme.isSelected()) {
                        antiVol[0] = true;
                    } else if (af.jCheckAnti.isSelected()) {
                        antiVol[1] = true;
                    } else if (af.jCheckMarquage.isSelected()) {
                        antiVol[2] = true;
                    } else if (af.jCheckSys.isSelected()) {
                        antiVol[3] = true;
                    } else if (af.jCheckAutre.isSelected()) {
                        antiVol[4] = true;
                    } else if (af.jCheckAucun.isSelected()) {
                        for (int i = 0; i < 5; i++) {
                            antiVol[i] = false;
                        }
                        antiVol[5] = true;
                    }
                    a.setSysAntiVol(antiVol);

                    Boolean[] sitCond = new Boolean[6];
                    for (int i = 0; i < 6; i++) {
                        sitCond[i] = false;
                    }

                    if (af.jRBSit1Y.isSelected()) {
                        sitCond[0] = true;
                    } else if (af.jRBSit2Y.isSelected()) {
                        sitCond[1] = true;
                    } else if (af.jRBSit3Y.isSelected()) {
                        sitCond[2] = true;
                    } else if (af.jRBSit4Y.isSelected()) {
                        sitCond[3] = true;
                    } else if (af.jRBSit5Y.isSelected()) {
                        sitCond[4] = true;
                    } else if (af.jRBSit6Y.isSelected()) {
                        sitCond[5] = true;
                    }
                    a.setDriverSit(sitCond);

                    a.setBundle(af.jRadioHabiY.isSelected());

                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JrbSit4N;
    private javax.swing.ButtonGroup bGroupRabais;
    private javax.swing.ButtonGroup bGroupSexe;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JCheckBox jCheckAlarme;
    private javax.swing.JCheckBox jCheckAnti;
    private javax.swing.JCheckBox jCheckAucun;
    private javax.swing.JCheckBox jCheckAutre;
    private javax.swing.JCheckBox jCheckMarquage;
    private javax.swing.JCheckBox jCheckSys;
    private javax.swing.JComboBox<String> jComboAnnee;
    private javax.swing.JComboBox<String> jComboKM;
    private javax.swing.JComboBox<String> jComboMarque;
    private javax.swing.JComboBox<String> jComboModel;
    private javax.swing.JFormattedTextField jFTextDOB;
    private javax.swing.JFormattedTextField jFTextTelephone;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelAnnee;
    private javax.swing.JLabel jLabelAnti;
    private javax.swing.JLabel jLabelCourriel;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelHabi;
    private javax.swing.JLabel jLabelKM;
    private javax.swing.JLabel jLabelMarque;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelSit1;
    private javax.swing.JLabel jLabelSit2;
    private javax.swing.JLabel jLabelSit3;
    private javax.swing.JLabel jLabelSit4;
    private javax.swing.JLabel jLabelSit5;
    private javax.swing.JLabel jLabelSit6;
    private javax.swing.JLabel jLabelSitTitle;
    private javax.swing.JLabel jLabelTele;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVec;
    private javax.swing.JPanel jPanelAnti;
    private javax.swing.JPanel jPanelFin;
    private javax.swing.JPanel jPanelHabi;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSit;
    private javax.swing.JPanel jPanelVec;
    private javax.swing.JRadioButton jRBSit1N;
    private javax.swing.JRadioButton jRBSit1Y;
    private javax.swing.JRadioButton jRBSit2N;
    private javax.swing.JRadioButton jRBSit2Y;
    private javax.swing.JRadioButton jRBSit3N;
    private javax.swing.JRadioButton jRBSit3Y;
    private javax.swing.JRadioButton jRBSit4Y;
    private javax.swing.JRadioButton jRBSit5N;
    private javax.swing.JRadioButton jRBSit5Y;
    private javax.swing.JRadioButton jRBSit6N;
    private javax.swing.JRadioButton jRBSit6Y;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioHabiN;
    private javax.swing.JRadioButton jRadioHabiY;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JScrollPane jScrollMain;
    private javax.swing.JScrollPane jScrollPaneHabi;
    private javax.swing.JSeparator jSep1;
    private javax.swing.JSeparator jSep2;
    private javax.swing.JSeparator jSep3;
    private javax.swing.JSeparator jSep4;
    private javax.swing.JTextField jTextAdresse;
    private javax.swing.JTextField jTextCourriel;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextPane jTextPaneHabi;
    private javax.swing.JTextField jTextPrenom;
    private javax.swing.ButtonGroup sitBG1;
    private javax.swing.ButtonGroup sitBG2;
    private javax.swing.ButtonGroup sitBG3;
    private javax.swing.ButtonGroup sitBG4;
    private javax.swing.ButtonGroup sitBG5;
    private javax.swing.ButtonGroup sitBG6;
    // End of variables declaration//GEN-END:variables

}
