/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp1;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Class primaire pour l'interface
 *
 * @author Jerry
 */
public class AssuranceFrame extends javax.swing.JFrame {

    /**
     * Creates new form AssuranceFrame
     */
    public AssuranceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGroupSexe = new javax.swing.ButtonGroup();
        sitBG1 = new javax.swing.ButtonGroup();
        sitBG2 = new javax.swing.ButtonGroup();
        sitBG3 = new javax.swing.ButtonGroup();
        sitBG4 = new javax.swing.ButtonGroup();
        sitBG5 = new javax.swing.ButtonGroup();
        sitBG6 = new javax.swing.ButtonGroup();
        bGroupRabais = new javax.swing.ButtonGroup();
        jScrollMain = new javax.swing.JScrollPane();
        jPanelMain = new javax.swing.JPanel();
        jSep1 = new javax.swing.JSeparator();
        jSep2 = new javax.swing.JSeparator();
        jSep3 = new javax.swing.JSeparator();
        jSep4 = new javax.swing.JSeparator();
        jPanelInfo = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jTextPrenom = new javax.swing.JTextField();
        jTextNom = new javax.swing.JTextField();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();
        jLabelDOB = new javax.swing.JLabel();
        jFTextDOB = new javax.swing.JFormattedTextField();
        jLabelTele = new javax.swing.JLabel();
        jFTextTelephone = new javax.swing.JFormattedTextField();
        jLabelAdresse = new javax.swing.JLabel();
        jTextAdresse = new javax.swing.JTextField();
        jLabelCourriel = new javax.swing.JLabel();
        jTextCourriel = new javax.swing.JTextField();
        jPanelVec = new javax.swing.JPanel();
        jLabelVec = new javax.swing.JLabel();
        jLabelAnnee = new javax.swing.JLabel();
        jComboAnnee = new javax.swing.JComboBox<>();
        jLabelMarque = new javax.swing.JLabel();
        jComboMarque = new javax.swing.JComboBox<>();
        jLabelModel = new javax.swing.JLabel();
        jComboModel = new javax.swing.JComboBox<>();
        jLabelKM = new javax.swing.JLabel();
        jComboKM = new javax.swing.JComboBox<>();
        jPanelAnti = new javax.swing.JPanel();
        jLabelAnti = new javax.swing.JLabel();
        jCheckAlarme = new javax.swing.JCheckBox();
        jCheckAnti = new javax.swing.JCheckBox();
        jCheckMarquage = new javax.swing.JCheckBox();
        jCheckSys = new javax.swing.JCheckBox();
        jCheckAutre = new javax.swing.JCheckBox();
        jCheckAucun = new javax.swing.JCheckBox();
        jPanelSit = new javax.swing.JPanel();
        jLabelSitTitle = new javax.swing.JLabel();
        jLabelSit1 = new javax.swing.JLabel();
        jLabelSit2 = new javax.swing.JLabel();
        jLabelSit3 = new javax.swing.JLabel();
        jLabelSit4 = new javax.swing.JLabel();
        jLabelSit5 = new javax.swing.JLabel();
        jLabelSit6 = new javax.swing.JLabel();
        jRBSit1Y = new javax.swing.JRadioButton();
        jRBSit1N = new javax.swing.JRadioButton();
        jRBSit2Y = new javax.swing.JRadioButton();
        jRBSit2N = new javax.swing.JRadioButton();
        jRBSit3Y = new javax.swing.JRadioButton();
        jRBSit3N = new javax.swing.JRadioButton();
        jRBSit4Y = new javax.swing.JRadioButton();
        JrbSit4N = new javax.swing.JRadioButton();
        jRBSit5Y = new javax.swing.JRadioButton();
        jRBSit5N = new javax.swing.JRadioButton();
        jRBSit6Y = new javax.swing.JRadioButton();
        jRBSit6N = new javax.swing.JRadioButton();
        jPanelHabi = new javax.swing.JPanel();
        jLabelHabi = new javax.swing.JLabel();
        jScrollPaneHabi = new javax.swing.JScrollPane();
        jTextPaneHabi = new javax.swing.JTextPane();
        jRadioHabiY = new javax.swing.JRadioButton();
        jRadioHabiN = new javax.swing.JRadioButton();
        jPanelFin = new javax.swing.JPanel();
        jButtonSub = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(554, 1350));

        jScrollMain.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollMain.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanelMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitle.setText("Information de base");

        jTextPrenom.setText("Prenom");
        jTextPrenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPrenomMouseClicked(evt);
            }
        });

        jTextNom.setText("Nom");
        jTextNom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextNomMouseClicked(evt);
            }
        });

        bGroupSexe.add(jRadioMale);
        jRadioMale.setText("Male");

        bGroupSexe.add(jRadioFemale);
        jRadioFemale.setText("Female");

        jLabelDOB.setText("Date de naissance");

        jFTextDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jFTextDOB.setText("yyyy-mm-dd");
        jFTextDOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTextDOBMouseClicked(evt);
            }
        });

        jLabelTele.setText("Numero telephone");

        try {
            jFTextTelephone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTextTelephone.setText("123-456-7890");
        jFTextTelephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFTextTelephoneMouseClicked(evt);
            }
        });

        jLabelAdresse.setText("Adresse complete");

        jTextAdresse.setText("1111 rue de la Redondance, Sherbrooke, PQ J1J 1J1");
        jTextAdresse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAdresseMouseClicked(evt);
            }
        });

        jLabelCourriel.setText("Adresse courriel");

        javax.swing.GroupLayout jPanelInfoLayout = new javax.swing.GroupLayout(jPanelInfo);
        jPanelInfo.setLayout(jPanelInfoLayout);
        jPanelInfoLayout.setHorizontalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCourriel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabelTitle))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioFemale)
                            .addComponent(jRadioMale)
                            .addComponent(jLabelTele))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFTextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jFTextDOB, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jTextAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabelAdresse))
                    .addGroup(jPanelInfoLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabelCourriel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelInfoLayout.setVerticalGroup(
            jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioMale)
                    .addComponent(jLabelDOB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioFemale)
                    .addComponent(jFTextDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTele)
                    .addComponent(jFTextTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelAdresse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCourriel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextCourriel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelVec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelVec.setText("Information du vehicule");

        jLabelAnnee.setText("Annee");

        jComboAnnee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009 et avant" }));

        jLabelMarque.setText("Marque");

        jComboMarque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dodge", "Jeep", "GMC", "Ram", "Nissan", "Hyundai", "Chevrolet", "Honda", "Toyota", "Ford" }));
        jComboMarque.setSelectedItem("");
        jComboMarque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboMarqueMouseClicked(evt);
            }
        });

        jLabelModel.setText("Model");

        jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Challenger", "Nitro", "Ram", "Omni", "Viper" }));

        jLabelKM.setText("KM annuelle");

        jComboKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15000 et moins", "15001 - 20000", "20001 - 25000", "25001 - 30000", "30001 - 35000", "35001 - 40000", "40001 - 45000", "45001 - 50000", "50001 - 55000", "55001 - 60000", "60001 - 65000", "65001 - 70000", "70001 - 75000", "75001 - 80000", "80001 - 85000", "85001 - 90000", "90001 - 95000", "95001 - 100000", "100000 et plus" }));

        javax.swing.GroupLayout jPanelVecLayout = new javax.swing.GroupLayout(jPanelVec);
        jPanelVec.setLayout(jPanelVecLayout);
        jPanelVecLayout.setHorizontalGroup(
            jPanelVecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAnnee)
                    .addComponent(jComboMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMarque)
                    .addComponent(jLabelModel)
                    .addComponent(jComboModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVec)
                    .addComponent(jLabelKM))
                .addContainerGap())
        );
        jPanelVecLayout.setVerticalGroup(
            jPanelVecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVec)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAnnee)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMarque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboMarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelModel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelKM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabelAnti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelAnti.setText("Systemes antivols");

        jCheckAlarme.setText("Alarme sonore");

        jCheckAnti.setText("Antidemarreur");

        jCheckMarquage.setText("Marquage intensif antivol");

        jCheckSys.setText("Systeme d'alarme de reperage");

        jCheckAutre.setText("Autre");

        jCheckAucun.setText("Aucun");

        javax.swing.GroupLayout jPanelAntiLayout = new javax.swing.GroupLayout(jPanelAnti);
        jPanelAnti.setLayout(jPanelAntiLayout);
        jPanelAntiLayout.setHorizontalGroup(
            jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckAnti)
                    .addComponent(jCheckAlarme)
                    .addComponent(jCheckSys)
                    .addComponent(jCheckAutre)
                    .addComponent(jCheckAucun)
                    .addGroup(jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelAnti)
                        .addComponent(jCheckMarquage)))
                .addContainerGap())
        );
        jPanelAntiLayout.setVerticalGroup(
            jPanelAntiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAntiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAnti)
                .addGap(27, 27, 27)
                .addComponent(jCheckAlarme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckAnti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckMarquage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckSys)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckAutre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckAucun)
                .addContainerGap())
        );

        jLabelSitTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSitTitle.setText("Situation du conducteur");

        jLabelSit1.setText("3 conducteurs/vechicules et plus");

        jLabelSit2.setText("Suspension de permis dans les 3 dernieres annees");

        jLabelSit3.setText("L'existence d'un dossier criminel");

        jLabelSit4.setText("Police d'assurance auto ou residentielle resiliee/refusee dans les 5 dernieres annees");

        jLabelSit5.setText("Conducteur perincipal detient un permis d'apprenti");

        jLabelSit6.setText("La valeur de votre vehicule est egale ou superieure a 100 000$");

        sitBG1.add(jRBSit1Y);
        jRBSit1Y.setText("Oui");

        sitBG1.add(jRBSit1N);
        jRBSit1N.setText("Non");

        sitBG2.add(jRBSit2Y);
        jRBSit2Y.setText("Oui");

        sitBG2.add(jRBSit2N);
        jRBSit2N.setText("Non");

        sitBG3.add(jRBSit3Y);
        jRBSit3Y.setText("Oui");

        sitBG3.add(jRBSit3N);
        jRBSit3N.setText("Non");

        sitBG4.add(jRBSit4Y);
        jRBSit4Y.setText("Oui");

        sitBG4.add(JrbSit4N);
        JrbSit4N.setText("Non");

        sitBG5.add(jRBSit5Y);
        jRBSit5Y.setText("Oui");

        sitBG5.add(jRBSit5N);
        jRBSit5N.setText("Non");

        sitBG6.add(jRBSit6Y);
        jRBSit6Y.setText("Oui");
        jRBSit6Y.setActionCommand("jRadioButton0");

        sitBG6.add(jRBSit6N);
        jRBSit6N.setText("Non");

        javax.swing.GroupLayout jPanelSitLayout = new javax.swing.GroupLayout(jPanelSit);
        jPanelSit.setLayout(jPanelSitLayout);
        jPanelSitLayout.setHorizontalGroup(
            jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSitLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSit4)
                    .addComponent(jLabelSit1)
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSit5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelSitLayout.createSequentialGroup()
                                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRBSit4Y, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRBSit5Y, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRBSit6Y))
                                .addGap(140, 140, 140)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JrbSit4N, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jRBSit5N, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jRBSit6N, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabelSit6)
                    .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelSitTitle)
                        .addGroup(jPanelSitLayout.createSequentialGroup()
                            .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRBSit2Y)
                                .addComponent(jLabelSit2)
                                .addComponent(jLabelSit3)
                                .addComponent(jRBSit3Y)
                                .addComponent(jRBSit1Y))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jRBSit3N)
                                .addComponent(jRBSit2N)
                                .addComponent(jRBSit1N)))))
                .addGap(12, 12, 12))
        );
        jPanelSitLayout.setVerticalGroup(
            jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSitTitle)
                .addGap(18, 18, 18)
                .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addComponent(jLabelSit1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelSitLayout.createSequentialGroup()
                                .addComponent(jRBSit1Y)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSit2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBSit2Y)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSit3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRBSit3Y))
                            .addGroup(jPanelSitLayout.createSequentialGroup()
                                .addComponent(jRBSit1N)
                                .addGap(28, 28, 28)
                                .addComponent(jRBSit2N)
                                .addGap(28, 28, 28)
                                .addComponent(jRBSit3N)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSit4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBSit4Y)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSit5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBSit5Y)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSit6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRBSit6Y))
                    .addGroup(jPanelSitLayout.createSequentialGroup()
                        .addComponent(JrbSit4N)
                        .addGap(28, 28, 28)
                        .addComponent(jRBSit5N)
                        .addGap(28, 28, 28)
                        .addComponent(jRBSit6N)))
                .addContainerGap())
        );

        jLabelHabi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHabi.setText("Rabais habitation");

        jScrollPaneHabi.setBorder(null);

        jTextPaneHabi.setEditable(false);
        jTextPaneHabi.setBackground(new java.awt.Color(240, 240, 240));
        jTextPaneHabi.setBorder(null);
        jTextPaneHabi.setText("Si votre habitation est assurée avec nous, nous vous offrons un rabais. Voulez-vous inclure ce rabais à votre soumission?");
        jTextPaneHabi.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextPaneHabi.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextPaneHabi.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPaneHabi.setViewportView(jTextPaneHabi);

        bGroupRabais.add(jRadioHabiY);
        jRadioHabiY.setText("Oui");

        bGroupRabais.add(jRadioHabiN);
        jRadioHabiN.setText("Non");

        javax.swing.GroupLayout jPanelHabiLayout = new javax.swing.GroupLayout(jPanelHabi);
        jPanelHabi.setLayout(jPanelHabiLayout);
        jPanelHabiLayout.setHorizontalGroup(
            jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHabiLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabelHabi))
                    .addComponent(jScrollPaneHabi, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHabiLayout.createSequentialGroup()
                        .addComponent(jRadioHabiY)
                        .addGap(35, 35, 35)
                        .addComponent(jRadioHabiN)
                        .addGap(135, 135, 135)))
                .addContainerGap())
        );
        jPanelHabiLayout.setVerticalGroup(
            jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHabiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHabi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelHabiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioHabiY)
                    .addComponent(jRadioHabiN))
                .addContainerGap())
        );

        jButtonSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSub.setText("Soumission");
        jButtonSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubMouseClicked(evt);
            }
        });

        jButtonClose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonClose.setText("Fermer");
        jButtonClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCloseMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFinLayout = new javax.swing.GroupLayout(jPanelFin);
        jPanelFin.setLayout(jPanelFinLayout);
        jPanelFinLayout.setHorizontalGroup(
            jPanelFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSub)
                .addGap(55, 55, 55)
                .addComponent(jButtonClose)
                .addContainerGap())
        );
        jPanelFinLayout.setVerticalGroup(
            jPanelFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSub)
                    .addComponent(jButtonClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSep2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSep1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSep3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSep4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(12, 12, 12))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanelVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelAnti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jPanelSit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jPanelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jPanelFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanelHabi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSep1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelVec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAnti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSep2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSep3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelHabi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSep4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollMain.setViewportView(jPanelMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Methode pour enlever l'adresse deja soumis
     *
     * @param evt
     */
    private void jTextAdresseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAdresseMouseClicked
        if ("1111 rue de la Redondance, Sherbrooke, PQ J1J 1J1".equals(this.jTextAdresse.getText())) {
            jTextAdresse.setText("");
        }

    }//GEN-LAST:event_jTextAdresseMouseClicked

    /**
     * Methode pour enlever le # tele deja soumis
     *
     * @param evt
     */
    private void jFTextTelephoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextTelephoneMouseClicked
        if ("123-456-7890".equals(this.jFTextTelephone.getText())) {
            jFTextTelephone.setText("");
        }
    }//GEN-LAST:event_jFTextTelephoneMouseClicked

    /**
     * Methode pour enlever le text de Nom
     *
     * @param evt
     */
    private void jTextNomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextNomMouseClicked
        if ("Nom".equals(this.jTextNom.getText())) {
            jTextNom.setText("");
        }
    }//GEN-LAST:event_jTextNomMouseClicked

    /**
     * Methode pour enlever le text de Prenom
     *
     * @param evt
     */
    private void jTextPrenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPrenomMouseClicked
        if ("Prenom".equals(this.jTextPrenom.getText())) {
            jTextPrenom.setText("");
        }
    }//GEN-LAST:event_jTextPrenomMouseClicked

    /**
     * Methode pour enlever le text du date de naissance
     *
     * @param evt
     */
    private void jFTextDOBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFTextDOBMouseClicked
        if ("yyyy-mm-dd".equals(this.jFTextDOB.getText())) {
            jFTextDOB.setText("");
        }
    }//GEN-LAST:event_jFTextDOBMouseClicked

    /**
     * Methode pour changer les modeles de voitures apres la marque choisi
     *
     * @param evt
     */
    private void jComboMarqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboMarqueMouseClicked
        if (null != String.valueOf(this.jComboMarque.getSelectedItem())) {
            switch (String.valueOf(this.jComboMarque.getSelectedItem())) {
                case "Dodge":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Challenger", "Nitro", "Ram", "Omni", "Viper"}));
                    break;
                case "Jeep":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"YJ", "Cherokee", "Commander", "Hortbed", "Wangler"}));
                    break;
                case "GMC":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Acadia", "Canyon", "Sierra", "Terrain", "Yukon"}));
                    break;
                case "Ram":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1500", "2500", "3500", "Cab", "Promaster"}));
                    break;
                case "Nissan":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"GT-R", "Micra", "Leaf", "Qashqai", "Sentra"}));
                    break;
                case "Hyundai":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Tucson", "Palisade", "Kona", "Sonata", "Veloster"}));
                    break;
                case "Chevrolet":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Camaro", "Corvette", "Cruze", "Spark", "Tahoe"}));
                    break;
                case "Honda":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Civic", "Fit", "Accord", "HR-V", "Odyssey"}));
                    break;
                case "Toyota":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Corolla", "RAV4", "Camry", "C-HR", "86", "Supra"}));
                    break;
                case "Ford":
                    jComboModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Mustand", "Fiesta", "Explorer", "Ranger", "EcoSport"}));
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_jComboMarqueMouseClicked

    /**
     * button soumission 1. Verification des champs non rempli 
     * 2. Verification des champs date de naissance, telephone et courriel 
     * Finallement, on passe les donnees de l'interface a la class Assurance
     *
     * @param evt
     */
    private void jButtonSubMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubMouseClicked
        JFrame f = new JFrame();

        if (this.jTextPrenom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(f, "Error: Prenom. Ex: Justin", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (this.jTextNom.getText().isEmpty()) {
            JOptionPane.showMessageDialog(f, "Error: Nom. Ex: Trudeau", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (!this.jRadioMale.isSelected() && !this.jRadioFemale.isSelected()) {
            JOptionPane.showMessageDialog(f, "Error: Sexe. Il faut etre male ou female", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if ("yyyy-mm-dd".equals(this.jFTextDOB.getText()) || this.jFTextDOB.getText().isEmpty()) {
            JOptionPane.showMessageDialog(f, "Error: Date de naissance. Ex: 1970-01-01", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (!this.jFTextTelephone.getText().matches("\\d{3}[-s]\\d{3}[-s]\\d{4}")) {
            JOptionPane.showMessageDialog(f, "Error: # Telephone. Ex: 819-123-4567", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (this.jTextAdresse.getText().isEmpty()) {
            JOptionPane.showMessageDialog(f, "Error: Adresse complete. Ex: 1111 rue de la Redondance, Sherbrooke, PQ J1J 1J1", "Alert", JOptionPane.WARNING_MESSAGE);
        } else if (!this.jTextCourriel.getText().matches("^(.+)@(.+)$")) {
            JOptionPane.showMessageDialog(f, "Error: Adresse courriel. Ex: test@test.com", "Alert", JOptionPane.WARNING_MESSAGE);
        } else {
            Assurance a = new Assurance();

            a.setPrenom(this.jTextPrenom.getText());
            a.setNom(this.jTextNom.getText());

            if (this.jRadioFemale.isSelected()) {
                a.setSexe('f');
            } else {
                a.setSexe('m');
            }

            a.setDdn(this.jFTextDOB.getText());
            a.setAge(DateUtil.yearsOld(this.jFTextDOB.getText()));
            a.setTelNum(this.jFTextTelephone.getText());
            a.setAdresse(this.jTextAdresse.getText());
            a.setEmail(this.jTextCourriel.getText());
            a.setVecYear(String.valueOf(this.jComboAnnee.getSelectedItem()));
            a.setVecYI(this.jComboAnnee.getSelectedIndex());
            a.setVecMake(String.valueOf(this.jComboMarque.getSelectedItem()));
            a.setVecMod(String.valueOf(this.jComboModel.getSelectedItem()));
            a.setKmPerYr(String.valueOf(this.jComboKM.getSelectedItem()));
            a.setKmPerI(this.jComboKM.getSelectedIndex());

            Boolean[] antiVol = new Boolean[6];
            for (int i = 0; i < 6; i++) {
                antiVol[i] = false;
            }

            if (this.jCheckAlarme.isSelected()) {
                antiVol[0] = true;
            }
            if (this.jCheckAnti.isSelected()) {
                antiVol[1] = true;
            }
            if (this.jCheckMarquage.isSelected()) {
                antiVol[2] = true;
            }
            if (this.jCheckSys.isSelected()) {
                antiVol[3] = true;
            }
            if (this.jCheckAutre.isSelected()) {
                antiVol[4] = true;
            }
            if (this.jCheckAucun.isSelected()) {
                for (int i = 0; i < 5; i++) {
                    antiVol[i] = false;
                }
                antiVol[5] = true;
            }
            a.setSysAntiVol(antiVol);

            Boolean[] sitCond = new Boolean[6];
            for (int i = 0; i < 6; i++) {
                sitCond[i] = false;
            }

            if (this.jRBSit1Y.isSelected()) {
                sitCond[0] = true;
            }
            if (this.jRBSit2Y.isSelected()) {
                sitCond[1] = true;
            }
            if (this.jRBSit3Y.isSelected()) {
                sitCond[2] = true;
            }
            if (this.jRBSit4Y.isSelected()) {
                sitCond[3] = true;
            }
            if (this.jRBSit5Y.isSelected()) {
                sitCond[4] = true;
            }
            if (this.jRBSit6Y.isSelected()) {
                sitCond[5] = true;
            }
            a.setDriverSit(sitCond);

            a.setBundle(this.jRadioHabiY.isSelected());

            a.calcPrime();

            a.print();

            a.displayPrime();
        }

    }//GEN-LAST:event_jButtonSubMouseClicked

    /**
     * Code pour fermer le program quand fermer est selectione
     *
     * @param evt
     */
    private void jButtonCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssuranceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                AssuranceFrame af = new AssuranceFrame();

                af.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JrbSit4N;
    private javax.swing.ButtonGroup bGroupRabais;
    private javax.swing.ButtonGroup bGroupSexe;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JCheckBox jCheckAlarme;
    private javax.swing.JCheckBox jCheckAnti;
    private javax.swing.JCheckBox jCheckAucun;
    private javax.swing.JCheckBox jCheckAutre;
    private javax.swing.JCheckBox jCheckMarquage;
    private javax.swing.JCheckBox jCheckSys;
    private javax.swing.JComboBox<String> jComboAnnee;
    private javax.swing.JComboBox<String> jComboKM;
    private javax.swing.JComboBox<String> jComboMarque;
    private javax.swing.JComboBox<String> jComboModel;
    private javax.swing.JFormattedTextField jFTextDOB;
    private javax.swing.JFormattedTextField jFTextTelephone;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelAnnee;
    private javax.swing.JLabel jLabelAnti;
    private javax.swing.JLabel jLabelCourriel;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelHabi;
    private javax.swing.JLabel jLabelKM;
    private javax.swing.JLabel jLabelMarque;
    private javax.swing.JLabel jLabelModel;
    private javax.swing.JLabel jLabelSit1;
    private javax.swing.JLabel jLabelSit2;
    private javax.swing.JLabel jLabelSit3;
    private javax.swing.JLabel jLabelSit4;
    private javax.swing.JLabel jLabelSit5;
    private javax.swing.JLabel jLabelSit6;
    private javax.swing.JLabel jLabelSitTitle;
    private javax.swing.JLabel jLabelTele;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelVec;
    private javax.swing.JPanel jPanelAnti;
    private javax.swing.JPanel jPanelFin;
    private javax.swing.JPanel jPanelHabi;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSit;
    private javax.swing.JPanel jPanelVec;
    private javax.swing.JRadioButton jRBSit1N;
    private javax.swing.JRadioButton jRBSit1Y;
    private javax.swing.JRadioButton jRBSit2N;
    private javax.swing.JRadioButton jRBSit2Y;
    private javax.swing.JRadioButton jRBSit3N;
    private javax.swing.JRadioButton jRBSit3Y;
    private javax.swing.JRadioButton jRBSit4Y;
    private javax.swing.JRadioButton jRBSit5N;
    private javax.swing.JRadioButton jRBSit5Y;
    private javax.swing.JRadioButton jRBSit6N;
    private javax.swing.JRadioButton jRBSit6Y;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioHabiN;
    private javax.swing.JRadioButton jRadioHabiY;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JScrollPane jScrollMain;
    private javax.swing.JScrollPane jScrollPaneHabi;
    private javax.swing.JSeparator jSep1;
    private javax.swing.JSeparator jSep2;
    private javax.swing.JSeparator jSep3;
    private javax.swing.JSeparator jSep4;
    private javax.swing.JTextField jTextAdresse;
    private javax.swing.JTextField jTextCourriel;
    private javax.swing.JTextField jTextNom;
    private javax.swing.JTextPane jTextPaneHabi;
    private javax.swing.JTextField jTextPrenom;
    private javax.swing.ButtonGroup sitBG1;
    private javax.swing.ButtonGroup sitBG2;
    private javax.swing.ButtonGroup sitBG3;
    private javax.swing.ButtonGroup sitBG4;
    private javax.swing.ButtonGroup sitBG5;
    private javax.swing.ButtonGroup sitBG6;
    // End of variables declaration//GEN-END:variables

}
